spring:
  datasource:
    url: ${AWS_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${AWS_USERNAME}
    password: ${AWS_PASSWORD}
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  servlet:
    multipart:
      maxFileSize: 10MB # ?? ??? ?? ??
      maxRequestSize: 30MB  # ? ?? ?? ??? ?? ??
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_IMG}
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false